### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by soegaard** [Khan/react-components#61]
The documentation on  http://khan.github.io/react-components/  says:

> In the author's limited experience, it's easiest to clone React Components as a subrepo (assuming Git).
> 
> git submodule add https://github.com/Khan/react-components.git react-components
>         
> Then simply use CommonJS requires pointing to the components within the subrepo.
> 
> var TeX = require('react-components/js/tex.jsx');
> React.render(<TeX>\nabla \cdot E = 4 \pi \rho</TeX>, domNode);

However:

    $ git submodule add https://github.com/Khan/react-components.git react-components
    $ cd react-components
    $ make

eventually leads to the error:

> 
> Error: Cannot find module './react-live-editor/live-editor.jsx' from '/Users/soegaard/Dropbox/GitHub/matematik-app/react-components'
>     at /Users/soegaard/Dropbox/GitHub/matematik-app/react-components/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
>     at load (/Users/soegaard/Dropbox/GitHub/matematik-app/react-components/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
>     at onex (/Users/soegaard/Dropbox/GitHub/matematik-app/react-components/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
>     at /Users/soegaard/Dropbox/GitHub/matematik-app/react-components/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
>     at FSReqWrap.oncomplete (fs.js:82:15)
> make: *** [docs/preview-bundle.js] Error 1
> 

This page:   https://github.com/Khan/react-components shows that `react-live-editor` is a submodule of `react-components` so the installation instructions ought to include a note on how to clone react-live-editor.

This command: 

     git submodule update --init --recursive

fetched the submodule for me.

Now `make` gets a little further:

> $ make
> npm install
> npm WARN package.json react-components@0.4.0 license should be a valid SPDX license expression
> /
> > react-components@0.4.0 prepublish /Users/soegaard/Dropbox/GitHub/matematik-app/react-components
> > node prepublish.js
> 
> reactify@0.15.0-dev node_modules/reactify
> ├── through@2.3.8
> └── react-tools@0.12.0-rc1 (esprima-fb@6001.1.0-dev-harmony-fb, commoner@0.10.4)
> ./node_modules/.bin/browserify -t [ reactify --es6 ] js/*.jsx -o bundle.js
> ./node_modules/.bin/browserify -d -t [ reactify --es6 ] reactify-components.jsx -o docs/preview-bundle.js
> pip install -r requirements.txt
> make: pip: No such file or directory
> make: *** [pydeps] Error 1

This means that I need to install Python...

I only need the TeX component - as mentioned in issue #53 it would be nice to have a simple to use the TeX component without the other components.

Question: Is it necessary to run make?  Or can I use the TeX component without?
                 (the documentation doesn't say whether to run make or not)

**Comment by spicyj** [comment]
You should be able to install react-components from npm and `require('react-components/tex')`. Not sure why the instructions suggest a submodule…

**Comment by soegaard** [comment]
Thanks for the hint. Eventually I decided to use KaTeX directly.
